### ISSUE TITLE
Preparing tabular data

### ISSUE THREAD

**Issue by yvesgit** [unpackAI/DL101#1]
While exploring a student's notebook, using the WMO Hurricane Survival Dataset, I got the followinf error:

"ValueError: Must have equal len keys and value when setting with an iterable"

After trying a number of things, I found 2 relevant matters. I gave the following indications to the students, and suggest that they get integrated into the Tabular Coursebook:

> 
1. Missing values
Execute this to see how many rows there are with at least 1 missing value

<your_data_frame>.isna().any(axis=1).sum()

If those rows are a small percentage of the total number of rows,  drop them like this, otherwise the pycarret setup will complain

<your_data_frame>.dropna(inplace=True)
<your_data_frame>.reset_index(inplace=True, drop=True)

2. A parameter in the setup
Add the this parameter in the signature of setup:
profile=False

It's surprising that you should have to do that, because when I look at the source code (by doing 
?? pycaret.classification.setup), that is the default value. But set it anyway: 

data_prep = setup(data, target = <your_target> , session_id=<some_id_number>, fix_imbalance=True, feature_selection = True, remove_multicollinearity = True, profile=False)

**Comment by jamescavanagh** [comment]
@yvesgit Hi Yves, I am going through this old issue. It looks like it may warrent more exploration into the internals of pycaret. Since Pycaret is a wrapper for many other libraries, it is possible to change  the kwargs of those internal libraries using a dictionary. 

However, it is not something  that the students can be expected to do. We're thinking of dropping Pycaret from DL201 because of how it brushes over a lot of this configuration. 

I am closing  the issue, if it is still a problem, please repost it an issue
